name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: { branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          base: "header, repositories"
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Kolkata
          config_padding: 10%

      - name: Personal Activities
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          base: "activity, community, metatdata"
          token: ${{ secrets.METRICS_TOKEN }}
          config_padding: 10%

      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: ""
          config_padding: 10%

      - name: Plugin Languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          base: ""
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          config_padding: 10%
          plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage


      - name: Plugin Posts Dev.to
        uses: lowlighter/metrics@latest
        with:
          filename: posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_posts: yes
          plugin_posts_source: dev.to
          base: ""


      - name: Plugin Habits
        uses: lowlighter/metrics@latest
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_from: 220
          plugin_habits_days: 15
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          base: ""
          config_timezone: Asia/Kolkata

      - name: Stackoverflow plugin
        uses: lowlighter/metrics@latest
        with:
          filename: stackoverflow.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 2975952
          plugin_stackoverflow_limit: 2
