name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: { branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # ======================================================================================
      # Display introduction
      - name: Introduction plugin
        uses: lowlighter/metrics@master
        with:
          filename: introduction.svg
          description: test
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_introduction: yes
      # ======================================================================================
      # Display Personal Metrics
      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          base: "header, repositories"
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Kolkata
          config_padding: 10%
      # ======================================================================================
      # Display Personal Activities
      - name: Personal Activities
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          base: "activity, community, metatdata"
          token: ${{ secrets.METRICS_TOKEN }}
          config_padding: 10%
      # ======================================================================================
      # Display Calendar
      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: ""
          config_padding: 10%
      # ======================================================================================
      # Display Used Languages
      - name: Plugin Languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          base: ""
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          config_padding: 10%
          plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
      # ======================================================================================
      # Display Posts dev.to
      - name: Plugin Posts Dev.to
        uses: lowlighter/metrics@latest
        with:
          filename: posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_posts: yes
          plugin_posts_source: dev.to
          base: ""
      # ======================================================================================
      # Display Habits
      - name: Plugin Habits
        uses: lowlighter/metrics@latest
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_from: 220
          plugin_habits_days: 15
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          base: ""
          config_timezone: Asia/Kolkata
      # ======================================================================================
      # Display Stackoverflow Stats
      - name: Stackoverflow plugin
        uses: lowlighter/metrics@latest
        with:
          filename: stackoverflow.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 2975952
          plugin_stackoverflow_limit: 0

      # ======================================================================================
      # GitHub skyline commits calendar
      - name: 🌇 GitHub Skyline 3D calendar
        uses: lowlighter/metrics@master
        with:
          filename: skyline.svg
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
      # ======================================================================================
      # Display comment reactions statistics
      - name: 🎭 Reactions plugin
        uses: lowlighter/metrics@master
        with:
          filename: reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
      # ======================================================================================
      # Display ratio of open/closed/merged issues and pull requests
      - name: 🎟️ Follow-up plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
      # ======================================================================================
      # Display number of line changed (this is part of base content "repositories" section, so you need to enable it)
      - name: 👨‍💻 Lines plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
      # ======================================================================================
      # Achievements
      - name: 🏆 Achievements
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: polyglot, stargazer, developer, contributor, octonaut