name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: { branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      # ======================================================================================
      # 🙋 Introduction

      # Display introduction (user)
      - name: 🙋 Introduction plugin
        uses: lowlighter/metrics@master
        with:
          filename: introduction.svg
          description: test
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_introduction: yes

      # ======================================================================================
      # 📈 Personal Metrics
      # Display Personal Metrics
      - name: 📈 Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          base: "header, repositories"
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Kolkata
          config_padding: 10%

      # ======================================================================================
      # 📰 Recent activity

      # Display recent activity
      - name: 📰 Personal Activities
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          base: "activity, community, metatdata"
          token: ${{ secrets.METRICS_TOKEN }}
          config_padding: 10%

      # ======================================================================================
      # 📅 Isometric commit calendar

      # Display isometric calendar (365 days)
      - name: 📅 Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: ""
          config_padding: 10%

      # ======================================================================================
      # 🈷️ Most used languages

      # Display most used languages
      - name: 🈷️ Plugin Languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          base: ""
          config_padding: 10%
          plugin_languages_details: bytes-size, percentage

      # ======================================================================================
      # ✒️ Recent posts

      # Display recent posts
      - name: ✒️ Plugin Posts Dev.to
        uses: lowlighter/metrics@latest
        with:
          filename: posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_posts: yes
          plugin_posts_limit: 5
          plugin_posts_source: dev.to
          base: ""

      # ======================================================================================
      # 💡 Coding habits

      # Display coding habits and recent activity
      - name: 💡 Plugin Habits
        uses: lowlighter/metrics@latest
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_from: 220
          plugin_habits_days: 15
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          base: ""
          config_timezone: Asia/Kolkata


      # ======================================================================================
      # 🗨️ Stackoverflow plugin

      # Display Stackoverflow metrics
      - name: 🗨️  Stackoverflow plugin
        uses: lowlighter/metrics@latest
        with:
          filename: stackoverflow.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 2975952
          plugin_stackoverflow_sections: ""


      # ======================================================================================
      # 🌇 GitHub Skyline 3D calendar

      # GitHub skyline commits calendar
      - name: 🌇 GitHub Skyline 3D calendar
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: skyline.svg
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1


      # ======================================================================================
      # 🎭 Comment reactions plugin

      # Display comment reactions statistics
      - name: 🎭 Reactions plugin
        uses: lowlighter/metrics@master
        with:
          filename: reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage

      # ======================================================================================
      # 🎟️ Follow-up of issues and pull requests

      # Display ratio of open/closed/merged issues and pull requests
      - name: 🎟️ Follow-up plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes


      # ======================================================================================
      # 👨‍💻 Lines of code changed

      # Display number of line changed
      - name: 👨‍💻 Lines plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes

      # ======================================================================================
      # 🏆 Achievements

      # Achievements
      - name: 🏆 Achievements
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: polyglot, stargazer, developer, contributor, octonaut